### ISSUE TITLE
宠汪汪验证问题

### ISSUE THREAD

**Issue by sxx1314** [ClassmateLin/scripts#22]
- alpine 的容器手动编译安装了opencv 3.4.15 
- 运行加载opencv应该正常了，但是到了下载图片验证阶段报错。
```
需要进行拼图验证!
myname, 获取服务器数据失败:(2, 'No such file or directory')
```
- 由于在alpine下编译opencv 4.x 的版本一直报错所以无法测试4.x的版本

**Comment by ClassmateLin** [comment]
之前本来用alpine镜像坑太多了，才换了slim-buster。下载图下载不了估计是pyppeteer模块的问题，有些依赖可能没有，我用slim-buster也安装了一些依赖解决这个问题。
